# Generated by Django 4.2.4 on 2023-09-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_book_price1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='images',
        ),
    ]
